---
- name: installs sshd daemon
  apt:
    name: openssh-server
    update_cache: yes

- name: create privilege separation directory
  file:
    path: /var/run/sshd
    state: directory
    mode: 0755
