# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
---
- hosts: all
  gather_facts: false
  tasks:
    - name: output project
      debug: 
        msg: "Project is {{PROJECT}}"

- hosts: tfc
  roles:
    - dumb-init
    - user_account
    - { role: github_python_module, user: "{{USER}}", url: "ssh://git@github.com:rstms/{{PROJECT}}.git" }
    #- sshd
  tasks:
    - name: write rc file
      shell: "echo '#!/bin/sh\nexec {{PROJECT}}' >/etc/rc"
    - name: make rc file executable
      shell: chmod +x /etc/rc
